<?php
    header('Content-Type: text/html; charset=utf-8');

    $rawDogApiResponse = file_get_contents("https://dog.ceo/api/breeds/image/random");
    $rawCatApiResponse = file_get_contents("https://api.thecatapi.com/v1/images/search");

    $dogUrl = json_decode($rawDogApiResponse, true)["message"];
    $catUrl = json_decode($rawCatApiResponse, true)[0]['url'];

?>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Random animals</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
              rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
              crossorigin="anonymous">
    </head>
    <body>
        <div class="container-fluid p-5 bg-primary text-white text-center">
            <h1>Hello. Here is random animals page.</h1>
        </div>
        <div class="container mt-5">
            <div class="row">
                <div class="col-sm-6">
                    <h3>Random Dog</h3>
                    <img src="<?php echo $dogUrl; ?>" alt="Random Dog">
                </div>
                <div class="col-sm-6">
                    <h3>Random Cat</h3>
                    <img src="<?php echo $catUrl; ?>" alt="Random Cat">
                </div>
            </div>
        </div>
    </body>
</html>